### ISSUE TITLE
Неуместный IO

### ISSUE THREAD

**Issue by alexmikhalevich** [DariaFil/Homework#9]
Зачем у тебя везде в коде всякие "печаталки"? Сейчас это не требовалось. Более того, в дальнейшем они тебе будут только вредить.

**Comment by DariaFil** [comment]
Я переделала структуру печаталок. Теперь вместо функций внутри классов объектов принтерами служат отдельные классы, наследующие от общего интерфейса, которые преобразуют принятый объект к определённому классу объекта (юнит, поле или армия) и производят его печать. Пока что все изменения в ветке dev.
